window.enums = {};

window.enums.repeat = [
    'oneHour',
    'sixHours',
    'twelveHours',
    'oneDay',
    'twoDays',
    'threeDays',
    'oneWeek',
    'never',
    'noLimit',
];

window.enums.treeType = [
    'conversation',
    'vmail',
    'document',
    'newspaper',
    'misc',
];

window.enums.triggerPoint = [
    'onNewTrackTarget',
    'onNewAction',
    'whileTickOnTrackTarget',
    'vmail',
    'telephone',
    'never',
    'newspaperMurder',
    'newspaperArticle',
];

window.enums.triggers = [
    'awake',
    'dead',
    'asleep',
    'unconscious',
    'noReactionState',
    'investigating',
    'investigatingVisual',
    'investigatingSound',
    'persuing',
    'searching',
    'notInCombat',
    'inCombat',
    'legal',
    'illegal',
    'travelling',
    'sat',
    'employee',
    'nonEmployee',
    'carrying',
    'notCarrying',
    'privateLocation',
    'publicLocation',
    'onStreet',
    'atHome',
    'atWork',
    'lightOnAny',
    'lightOnMain',
    'allLightsOff',
    'rain',
    'indoors',
    'brokenSign',
    'travellingToWork',
    'notPresent',
    'atEatery',
    'hasJob',
    'unemployed',
    'homeIntenseWallpaper',
    'homeBrightSign',
    'enforcerOnDuty',
    'notEnforcerOnDuty',
    'trespassing',
    'locationOfAuthority',
    'drunk',
    'restrained',
    'sober',
];

window.enums.connection = [
    'friend',
    'neighbor',
    'housemate',
    'lover',
    'boss',
    'workTeam',
    'workOther',
    'regularCustomer',
    'regularStaff',
    'familiarResidence',
    'familiarWork',
    'publicFigure',
    'stranger',
    'paramour',
    'player',
    'anyoneNotPlayer',
    'friendOrWork',
    'knowsName',
    'anyAcquaintance',
    'anyone',
    'workNotBoss',
    'relationshipMatch',
    'corpDove',
    'spamVmail',
    'corpStarch',
    'corpIndigo',
    'corpKaizen',
    'corpElgen',
    'corpCandor',
    'flairQuotes',
    'randomSpamVmail',
    'noReplyVmail',
    'bookGrubs',
    'pestControl',
    'landlord',
    'groupMember',
    'storyPartner',
];

window.enums.traitConditions = [
  'IfAnyOfThese',
  'IfAllOfThese',
  'IfNoneOfThese',
  'otherAnyOfThese',
  'otherAllOfThese',
  'otherNoneOfThese',
];

window.enums.traitCondition = window.enums.traitConditions;